apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: 672930000772.dkr.ecr.ap-south-1.amazonaws.com/node_app:latest
          ports:
            - containerPort: 3005
